In [38]:
# Import Necessary libraries

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
# Import dataset
df_hour = pd.read_csv("train.csv")
df_hour.head(10)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1
5,2011-01-01 05:00:00,1,0,0,2,9.84,12.880,75,6.0032,0,1,1
6,2011-01-01 06:00:00,1,0,0,1,9.02,13.635,80,0.0000,2,0,2
7,2011-01-01 07:00:00,1,0,0,1,8.20,12.880,86,0.0000,1,2,3
8,2011-01-01 08:00:00,1,0,0,1,9.84,14.395,75,0.0000,1,7,8
9,2011-01-01 09:00:00,1,0,0,1,13.12,17.425,76,0.0000,8,6,14

#### Data Wrangling

In [20]:
# Check the number of rows and columns
df_hour.shape

(10886, 12)

In [35]:
# Get an overview of columns, their data types and possible missing values.
df_hour.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   season      10886 non-null  object
 1   holiday     10886 non-null  int64
 2   workingday  10886 non-null  int64
 3   weather     10886 non-null  object
 4   temp        10886 non-null  float64
 5   atemp       10886 non-null  float64
 6   humidity    10886 non-null  int64
 7   windspeed   10886 non-null  float64
 8   count       10886 non-null  int64
 9   hour        10886 non-null  int32
 10  month       10886 non-null  object
 11  dayofweek   9335 non-null   object
 12  year        10886 non-null  int32
dtypes: float64(3), int32(2), int64(4), object(4)
memory usage: 1020.7+ KB

In [41]:
# Confirm that there are truly no missing values
print(df_hour.isna().sum())

# Not necessary, but cross-checking the number of columns with no missing values 
print()
print(df_hour.notna().sum())

season           0
holiday          0
workingday       0
weather          0
temp             0
atemp            0
humidity         0
windspeed        0
count            0
hour             0
month            0
dayofweek     1551
year             0
dtype: int64

season        10886
holiday       10886
workingday    10886
weather       10886
temp          10886
atemp         10886
humidity      10886
windspeed     10886
count         10886
hour          10886
month         10886
dayofweek      9335
year          10886
dtype: int64

In [23]:
# Identify and handle duplicates across the entire dataset
print(df_hour.duplicated().sum())

0

In [24]:
# Drop the 'casual' and 'registered' columns since they both add up to form the 'count' column
df_hour = df_hour.drop(['casual', 'registered'], axis=1)

In [25]:
# Convert the datetime from object to a datetime dtype first
df_hour['datetime'] = pd.to_datetime(df_hour['datetime'])

# Extract the datetime components into separate columns
df_hour['hour'] = df_hour['datetime'].dt.hour
df_hour['month'] = df_hour['datetime'].dt.month
df_hour['dayofweek'] = df_hour['datetime'].dt.dayofweek
df_hour['year'] = df_hour['datetime'].dt.year

# Drop the object column
df_hour.drop('datetime', axis=1, inplace=True)

In [26]:
# Review the data again
df_hour.head()

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,count,hour,month,dayofweek,year
0,1,0,0,1,9.84,14.395,81,0.0,16,0,1,5,2011
1,1,0,0,1,9.02,13.635,80,0.0,40,1,1,5,2011
2,1,0,0,1,9.02,13.635,80,0.0,32,2,1,5,2011
3,1,0,0,1,9.84,14.395,75,0.0,13,3,1,5,2011
4,1,0,0,1,9.84,14.395,75,0.0,1,4,1,5,2011

### Data Formatting
Ensuring Appropriate data types for the sake of EDA

In [27]:
# Map the seasons based on kaggle documentation
season_map = {
    1: 'Spring',
    2: 'Summer',
    3: 'Fall',
    4: 'Winter'
}

df_hour['season'] = df_hour['season'].map(season_map)
df_hour['season'].head()

0    Spring
1    Spring
2    Spring
3    Spring
4    Spring
Name: season, dtype: object

In [28]:
# Map weather for clearer charts (based on docs too)
weather_map = {
    1: 'Clear',
    2: 'Misty',
    3: 'Light_Precip',
    4: 'Heavy_Precip'
}

df_hour['weather'] = df_hour['weather'].map(weather_map)
df_hour['weather'].head()

0    Clear
1    Clear
2    Clear
3    Clear
4    Clear
Name: weather, dtype: object

In [29]:
# Change data type from int to categorical for the variable 'month'
month_string = {
    1: 'January',
    2: 'February',
    3: 'March',
    4: 'April',
    5: 'May',
    6: 'June',
    7: 'July',
    8: 'August',
    9: 'September',
    10: 'October',
    11: 'November',
    12: 'December'
}

df_hour['month'] = df_hour['month'].map(month_string)
df_hour['month'].head()

0    January
1    January
2    January
3    January
4    January
Name: month, dtype: object

In [30]:
# Change data type from int to categorical for the variable 'dayofweek'
weekday_string = {
    1: 'Monday',
    2: 'Tuesday',
    3: 'Wednesday',
    4: 'Thursday',
    5: 'Friday',
    6: 'Saturday',
    '7': 'Sunday'
}

df_hour['dayofweek'] = df_hour['dayofweek'].map(weekday_string)
df_hour['dayofweek'].head()

0    Friday
1    Friday
2    Friday
3    Friday
4    Friday
Name: dayofweek, dtype: object

In [31]:
df_hour.head()

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,count,hour,month,dayofweek,year
0,Spring,0,0,Clear,9.84,14.395,81,0.0,16,0,January,Friday,2011
1,Spring,0,0,Clear,9.02,13.635,80,0.0,40,1,January,Friday,2011
2,Spring,0,0,Clear,9.02,13.635,80,0.0,32,2,January,Friday,2011
3,Spring,0,0,Clear,9.84,14.395,75,0.0,13,3,January,Friday,2011
4,Spring,0,0,Clear,9.84,14.395,75,0.0,1,4,January,Friday,2011

### Data Normalisation
To ensure consistency and comparability & accoring to docs provided by UCI ML repo

In [32]:
# Normalise data
df_hour['temp'] = (df_hour['temp']) * 47 - 8
df_hour['atemp'] = (df_hour['atemp']) * 66 - 16
df_hour['humidity'] = (df_hour['humidity']) * 100
df_hour['windspeed'] = (df_hour['windspeed']) * 67

### Data Binning for Categorization

In [33]:
# Define